name: Football Monitor

on:
  schedule:
    # Ejecutar cada 30 minutos entre 1 PM y 6 AM (UTC)
    # Dividido en dos rangos porque cruza medianoche:
    - cron: '*/30 13-23 * * *'   # 1 PM a 11 PM (mismo día UTC)
    - cron: '*/30 0-6 * * *'     # 12 AM a 6 AM (día siguiente UTC)
  
  # Permite ejecutar manualmente
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Install jq
      run: sudo apt-get update && sudo apt-get install -y jq
    
    - name: Make script executable
      run: chmod +x ./football_monitor.sh
    
    - name: Run football monitor
      run: ./football_monitor.sh
      env:
        # Usar Repository Secrets
        BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
