name: Football Monitor PowerShell

on:
  schedule:
    # Execute every 15 minutes between 1 PM and 6 AM (UTC)
    # Split into two ranges because it crosses midnight:
    - cron: '*/15 13-23 * * *'   # 1 PM to 11 PM UTC
    - cron: '*/15 0-6 * * *'     # 12 AM to 6 AM UTC
  
  # Allow manual execution
  workflow_dispatch:

jobs:
  monitor:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Run football monitor
      shell: pwsh
      run: .\football_monitor.ps1
      env:
        # Use Repository Secrets
        BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
